### PR TITLE
Add ESP8266 to RwReg definition

### PR DESCRIPTION
**Pull request by agrath**
Adds the ESP8266 to the RwReg ifdef as per adafruit#21 but on a clean fork so should merge

### CODE REVIEW

**Comment by agrath** [comment]
Build fails but looks like a Travis CI issue as all platforms fail due to not finding arduino

**Comment by ladyada** [comment]
yeah https://downloads.arduino.cc/ is having problems!

**Comment by ladyada** [comment]
@siddacious please re-run this PR after actioning

**Comment by siddacious** [comment]
will do

**Comment by ladyada** [comment]
added by hand. note esp does not have 2 analog pins.

**Pull request closed without merging**
